# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental_studio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appt_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appt_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appt_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appt_datetime',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appt_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appt_by_name',
            new_name='name',
        ),
    ]
