# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental_studio', '0004_auto_20170916_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appt_gender',
            new_name='gender',
        ),
    ]
