# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental_studio', '0002_auto_20170916_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='first_appt_date',
            new_name='first_appointment_date',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_lname',
            new_name='last_name',
        ),
    ]
