# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_studio', '0003_auto_20170916_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(verbose_name='Appointment date'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_appointment_date',
            field=models.DateTimeField(verbose_name='Registration Date'),
        ),
    ]
