# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dental_studio', '0005_auto_20170916_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='treatment_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='treatment_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='treatment_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='user',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
